import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Navbar } from "@/components/layout";
import { containerClasses } from "@/lib/layout-classes";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} font-sans antialiased min-h-screen flex flex-col bg-foreground text-background`}
      >
        <Navbar />
        <div className={`${containerClasses} flex-1 flex flex-col`}>
          {children}
        </div>
      </body>
    </html>
  );
}
